name: Deploy to Firebase Hosting (Production)

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build & Bundle
      run: |
        npm install
        npm i -g firebase-tools
        npm run build:ts
        npm run bundle
    - name: Test
      run: |
        npm run test
    - name: Deploy 
      run: |
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting,functions --message ${{ github.sha }}
      env:
        CI: true
