name: Firebase Hosting - Web (Production)

on: 
  push:
    branches: 
      - i8

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build & Bundle
      run: |
        npm install
        npm i -g firebase-tools
        npm run build:ts
        npm run bundle
        npm run test
    - name: Test
        npm run test
    - name: Deploy 
        firebase use bhhc-se2-tsa --token ${{ secrets.FIREBASE_TOKEN }}
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting
      env:
        CI: true
