name: Deploy to Firebase Hosting (Production)

on: 
  push:
    branches: 
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [8.x]

    steps:
    - uses: actions/checkout@v1
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: Build & Bundle
      run: |
        npm install
        npm i -g firebase-tools
        npm run build:ts
        npm run bundle
    - name: Test
      run: |
        npm run test
    - name: Emulate Local - Test Deployable Services
      run: |
        npm run emulate:stack
       ./node_modules/.bin/newman run https://api.getpostman.com/collections/9563315-53cd1b2f-21de-4e20-b94f-97ca0c7c1f9f?apikey=${{ secrets.POSTMAN_API_KEY }} -e https://api.getpostman.com/environments/9563315-ace70801-6d11-4504-b96a-b2cfabb9abf9?apikey=${{ secrets.POSTMAN_API_KEY }} -r cli 
    - name: Deploy 
      run: |
        firebase deploy --token ${{ secrets.FIREBASE_TOKEN }} --only hosting,functions --message ${{ github.sha }}
    - name: Post-Deploy Production Service Integration Tests
      run: |
        ./node_modules/.bin/newman run https://api.getpostman.com/collections/9563315-53cd1b2f-21de-4e20-b94f-97ca0c7c1f9f?apikey=${{ secrets.POSTMAN_API_KEY }} -e https://api.getpostman.com/environments/9563315-695708fa-4101-4ac3-bda2-b85cf316d1c1?apikey=${{ secrets.POSTMAN_API_KEY }} -r cli 
      env:
        CI: true
